version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/wp-content/themes/sac-saentis-2016
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
